package Model;
// Generated 26/09/2015 21:44:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="vendas"
)
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nome;
     private String endereco;
     private String email;
     private String bairro;
     private String cidade;
     private String cep;
     private String estado;
     private String fone;
     private String celular;
     private String cpf;
     private String obs;
     private String rg;
     private String orgaorg;
     private Date nascimento;
     private Date desde;
     private String cnpj;
     private String insest;
     private String sexo;
     private String profissao;
     private String empresa;
     private String foneemp;
     private Double renda;
     private String referencia;
     private String foneref;

    public Cliente() {
    }

    public Cliente(String nome, String endereco, String email, String bairro, String cidade, String cep, String estado, String fone, String celular, String cpf, String obs, String rg, String orgaorg, Date nascimento, Date desde, String cnpj, String insest, String sexo, String profissao, String empresa, String foneemp, Double renda, String referencia, String foneref) {
       this.nome = nome;
       this.endereco = endereco;
       this.email = email;
       this.bairro = bairro;
       this.cidade = cidade;
       this.cep = cep;
       this.estado = estado;
       this.fone = fone;
       this.celular = celular;
       this.cpf = cpf;
       this.obs = obs;
       this.rg = rg;
       this.orgaorg = orgaorg;
       this.nascimento = nascimento;
       this.desde = desde;
       this.cnpj = cnpj;
       this.insest = insest;
       this.sexo = sexo;
       this.profissao = profissao;
       this.empresa = empresa;
       this.foneemp = foneemp;
       this.renda = renda;
       this.referencia = referencia;
       this.foneref = foneref;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcliente", unique=true, nullable=false)
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="endereco", length=50)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="bairro", length=30)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="fone", length=10)
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }

    
    @Column(name="celular", length=10)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="cpf", length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="obs", length=405)
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }

    
    @Column(name="rg", length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="orgaorg", length=10)
    public String getOrgaorg() {
        return this.orgaorg;
    }
    
    public void setOrgaorg(String orgaorg) {
        this.orgaorg = orgaorg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nascimento", length=10)
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="desde", length=10)
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }

    
    @Column(name="cnpj", length=14)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="insest", length=20)
    public String getInsest() {
        return this.insest;
    }
    
    public void setInsest(String insest) {
        this.insest = insest;
    }

    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="profissao", length=20)
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    
    @Column(name="empresa", length=45)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="foneemp", length=10)
    public String getFoneemp() {
        return this.foneemp;
    }
    
    public void setFoneemp(String foneemp) {
        this.foneemp = foneemp;
    }

    
    @Column(name="renda", precision=22, scale=0)
    public Double getRenda() {
        return this.renda;
    }
    
    public void setRenda(Double renda) {
        this.renda = renda;
    }

    
    @Column(name="referencia", length=45)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="foneref", length=10)
    public String getFoneref() {
        return this.foneref;
    }
    
    public void setFoneref(String foneref) {
        this.foneref = foneref;
    }




}


