package Model;
// Generated 26/09/2015 21:44:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DVenda generated by hbm2java
 */
@Entity
@Table(name="d_venda"
    ,catalog="vendas"
)
public class DVenda  implements java.io.Serializable {


     private Integer iddVenda;
     private Integer CVendaCodigo;
     private String produtoCodigo;
     private Integer quantidade;
     private Double valorUnitario;
     private Double valorTotal;

    public DVenda() {
    }

    public DVenda(Integer CVendaCodigo, String produtoCodigo, Integer quantidade, Double valorUnitario, Double valorTotal) {
       this.CVendaCodigo = CVendaCodigo;
       this.produtoCodigo = produtoCodigo;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
       this.valorTotal = valorTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idd_venda", unique=true, nullable=false)
    public Integer getIddVenda() {
        return this.iddVenda;
    }
    
    public void setIddVenda(Integer iddVenda) {
        this.iddVenda = iddVenda;
    }

    
    @Column(name="c_venda_codigo")
    public Integer getCVendaCodigo() {
        return this.CVendaCodigo;
    }
    
    public void setCVendaCodigo(Integer CVendaCodigo) {
        this.CVendaCodigo = CVendaCodigo;
    }

    
    @Column(name="produto_codigo", length=20)
    public String getProdutoCodigo() {
        return this.produtoCodigo;
    }
    
    public void setProdutoCodigo(String produtoCodigo) {
        this.produtoCodigo = produtoCodigo;
    }

    
    @Column(name="quantidade")
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_unitario", precision=22, scale=0)
    public Double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(Double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    
    @Column(name="valor_total", precision=22, scale=0)
    public Double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Double valorTotal) {
        this.valorTotal = valorTotal;
    }




}


