package Model;
// Generated 26/09/2015 21:44:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="vendas"
)
public class Fornecedor  implements java.io.Serializable {


     private Integer idfornecedor;
     private String nome;
     private String endereco;
     private String email;
     private String bairro;
     private String cidade;
     private String cep;
     private String estado;
     private String fone;
     private String celular;
     private String cpf;
     private String obs;
     private String rg;
     private String orgaorg;
     private Date desde;
     private String cnpj;
     private String insest;
     private String contato;

    public Fornecedor() {
    }

    public Fornecedor(String nome, String endereco, String email, String bairro, String cidade, String cep, String estado, String fone, String celular, String cpf, String obs, String rg, String orgaorg, Date desde, String cnpj, String insest, String contato) {
       this.nome = nome;
       this.endereco = endereco;
       this.email = email;
       this.bairro = bairro;
       this.cidade = cidade;
       this.cep = cep;
       this.estado = estado;
       this.fone = fone;
       this.celular = celular;
       this.cpf = cpf;
       this.obs = obs;
       this.rg = rg;
       this.orgaorg = orgaorg;
       this.desde = desde;
       this.cnpj = cnpj;
       this.insest = insest;
       this.contato = contato;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idfornecedor", unique=true, nullable=false)
    public Integer getIdfornecedor() {
        return this.idfornecedor;
    }
    
    public void setIdfornecedor(Integer idfornecedor) {
        this.idfornecedor = idfornecedor;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="endereco", length=45)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="email", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="bairro", length=30)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="fone", length=10)
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }

    
    @Column(name="celular", length=10)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="cpf", length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="obs", length=200)
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }

    
    @Column(name="rg", length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="orgaorg", length=10)
    public String getOrgaorg() {
        return this.orgaorg;
    }
    
    public void setOrgaorg(String orgaorg) {
        this.orgaorg = orgaorg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="desde", length=10)
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }

    
    @Column(name="cnpj", length=14)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="insest", length=20)
    public String getInsest() {
        return this.insest;
    }
    
    public void setInsest(String insest) {
        this.insest = insest;
    }

    
    @Column(name="contato", length=20)
    public String getContato() {
        return this.contato;
    }
    
    public void setContato(String contato) {
        this.contato = contato;
    }




}


