package Model;
// Generated 26/09/2015 21:44:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="vendas"
)
public class Produto  implements java.io.Serializable {


     private Integer idproduto;
     private Integer fornecedorCodigo;
     private String descricao;
     private Double vlrcompra;
     private Double vlrvenda;
     private Integer estoque;
     private Integer critico;

    public Produto() {
    }

    public Produto(Integer fornecedorCodigo, String descricao, Double vlrcompra, Double vlrvenda, Integer estoque, Integer critico) {
       this.fornecedorCodigo = fornecedorCodigo;
       this.descricao = descricao;
       this.vlrcompra = vlrcompra;
       this.vlrvenda = vlrvenda;
       this.estoque = estoque;
       this.critico = critico;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproduto", unique=true, nullable=false)
    public Integer getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(Integer idproduto) {
        this.idproduto = idproduto;
    }

    
    @Column(name="fornecedor_codigo")
    public Integer getFornecedorCodigo() {
        return this.fornecedorCodigo;
    }
    
    public void setFornecedorCodigo(Integer fornecedorCodigo) {
        this.fornecedorCodigo = fornecedorCodigo;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="vlrcompra", precision=22, scale=0)
    public Double getVlrcompra() {
        return this.vlrcompra;
    }
    
    public void setVlrcompra(Double vlrcompra) {
        this.vlrcompra = vlrcompra;
    }

    
    @Column(name="vlrvenda", precision=22, scale=0)
    public Double getVlrvenda() {
        return this.vlrvenda;
    }
    
    public void setVlrvenda(Double vlrvenda) {
        this.vlrvenda = vlrvenda;
    }

    
    @Column(name="estoque")
    public Integer getEstoque() {
        return this.estoque;
    }
    
    public void setEstoque(Integer estoque) {
        this.estoque = estoque;
    }

    
    @Column(name="critico")
    public Integer getCritico() {
        return this.critico;
    }
    
    public void setCritico(Integer critico) {
        this.critico = critico;
    }




}


