package Model;
// Generated 26/09/2015 21:44:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name="venda"
    ,catalog="vendas"
)
public class Venda  implements java.io.Serializable {


     private Integer idvenda;
     private Integer clienteCodigo;
     private Date dataVenda;

    public Venda() {
    }

    public Venda(Integer clienteCodigo, Date dataVenda) {
       this.clienteCodigo = clienteCodigo;
       this.dataVenda = dataVenda;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvenda", unique=true, nullable=false)
    public Integer getIdvenda() {
        return this.idvenda;
    }
    
    public void setIdvenda(Integer idvenda) {
        this.idvenda = idvenda;
    }

    
    @Column(name="cliente_codigo")
    public Integer getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(Integer clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_venda", length=10)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }




}


